import { images } from "./images";

export const products = [
  {
    id: 1,
    name: "Urban Runner Pro",
    price: "Rp129.99",
    colors: ["#000000", "#3B82F6", "#EF4444"],
    isNew: true,
    image: images.bunga_1a,
    additionalImages: [images.bunga_1b, images.bunga_1c, images.bunga_1d],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "flowers",
  },
  {
    id: 2,
    name: "Classic Comfort",
    price: "Rp99.99",
    colors: ["#6B7280", "#10B981"],
    isNew: false,
    image: images.bunga_2a,
    additionalImages: [images.bunga_2b, images.bunga_2c],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "flowers",
  },
  {
    id: 3,
    name: "Classic Comfort",
    price: "Rp99.99",
    colors: ["#6B7280", "#10B981"],
    isNew: false,
    image: images.bunga_3a,
    additionalImages: [images.bunga_3b, images.bunga_3c, images.bunga_3d],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "flowers",
  },
  {
    id: 4,
    name: "Classic Comfort",
    price: "Rp99.99",
    colors: ["#6B7280", "#10B981"],
    isNew: false,
    image: images.bracelet_1a,
    additionalImages: [],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "bracelets",
  },
  {
    id: 5,
    name: "Classic Comfort",
    price: "Rp99.99",
    colors: ["#6B7280", "#10B981"],
    isNew: false,
    image: images.bracelet_2a,
    additionalImages: [],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "bracelets",
  },
  {
    id: 6,
    name: "Classic Comfort",
    price: "Rp99.99",
    colors: ["#6B7280", "#10B981"],
    isNew: false,
    image: images.bracelet_3a,
    additionalImages: [],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "bracelets",
  },
  {
    id: 7,
    name: "Classic Comfort",
    price: "Rp99.99",
    colors: ["#6B7280", "#10B981"],
    isNew: false,
    image: images.bags_1a,
    additionalImages: [],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "bags",
  },
  {
    id: 8,
    name: "Classic Comfort",
    price: "Rp99.99",
    colors: ["#6B7280", "#10B981"],
    isNew: false,
    image: images.bags_2a,
    additionalImages: [],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "bags",
  },
  {
    id: 9,
    name: "Classic Comfort",
    price: "Rp99.99",
    colors: ["#6B7280", "#10B981"],
    isNew: false,
    image: images.bags_3a,
    additionalImages: [],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "bags",
  },
];
